<?php

/* Get Latest Omeka Item. */

$url = 'http://exhibits.library.gwu.edu/api/items';

$headerArray = get_headers($url, 1);
$howMany = ceil($headerArray['Omeka-Total-Results'] / 50);
$json_string = "http://exhibits.library.gwu.edu/api/items?page=" . $howMany;
$jsondata = file_get_contents($json_string);
$itemArray  = json_decode($jsondata, true); // decode JSON to associative array
$itemArrayDesc = array_reverse($itemArray);

//$omekaItem = "Test Text <a href='http://exhibits.library.gwu.edu/items/show/" . $itemArrayDesc['id']  . "'>" . $itemArrayDesc['element_texts'][0]['text'] . "</a>";

$i = 0;
foreach($itemArrayDesc as $info){
  $theVar = $info['files']['url'];
  $json_string2 = $theVar;
  $jsondata2 = file_get_contents($json_string2);
  $itemArray2  = json_decode($jsondata2, true);
    foreach($itemArray2 as $info2){
    // gets file paths for images
    }
  // outputs things like echo "<li><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></li>";
  if (++$i == 7) break;
}

$omekaItem = "<div style='margin:.5em .1em .5em;'><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'><img style='border:1px solid #ccc;' src='" . $info2['file_urls']['thumbnail'] . "'></a></div><p><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></p><p style='margin-bottom:0; font-size:.95em;'>See all our <a href='http://exhibits.library.gwu.edu/'>Online Exhibits <i style='font-size:.9em;' class='fa fa-external-link'></i></a></p>";

$GLOBALS['omekaItem'] = $omekaItem;

/* End Omeka Item. */

/* Get Latest DCAAP Tumblr Item. */

//$dcaap_url = 'http://api.tumblr.com/v2/blog/dcaap.tumblr.com/posts';

        // set cache file name and path
        $cacheFile = 'showcaseCache-dcaap';
        $path = '/tmp/' . $cacheFile . '.cache';
        
        // checks to see if cached file is older than 1 hour (3600, units in seconds per UNIX/POSIX time), if so updates cache
        if ((!file_exists($path) || time() - filemtime($path) > 3600) && $cache = fopen($path, 'w+'))
        {
            $dcaap_url = 'http://api.tumblr.com/v2/blog/dcaap.tumblr.com/posts'; // get block from scratch if old
            fwrite($cache, $dcaap_url); // write block to cache
            fclose($cache);
        }
        else
        {
            $dcaap_url = file_get_contents($path); // get block from cache file
        }

//$headerArray = get_headers($url, 1);
//$howMany = ceil($headerArray['Omeka-Total-Results'] / 50);
//$json_string = "http://exhibits.library.gwu.edu/api/items?page=" . $howMany;
$jsondata3 = file_get_contents($dcaap_url);
$itemArray3  = json_decode($jsondata3, true); // decode JSON to associative array
//$itemArrayDesc2 = array_reverse($itemArray2);

$i = 0;
foreach($itemArray3 as $info3){
  
  //$theVar = $info3['posts'][0]['trail']['0']['post']['id'];
  $theVar = $info3['posts'][0]['photos']['0']['alt_sizes'][3]['url'];
  $postURL = $info3['posts'][0]['post_url'];

  $json_string = $dcaap_url;
  $jsondata = file_get_contents($json_string);

  //cleanup tumblr json
  //$jsondata3 = str_replace('var tumblr_api_read = ','',$jsondata3);
  //$jsondata3 = str_replace(';','',$jsondata3);

  $itemArray  = json_decode($jsondata, true);
    foreach($itemArray as $info30){
    // gets file paths for images
    }
  // outputs things like echo "<li><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></li>";
  if (++$i == 7) break;
}

//$dcaapItem = "<div>String from item for testing:" . $theVar . "</div>";

$dcaapItem = "<div style='margin:.5em .1em .5em;'><a href='" . $postURL . "'><img style='border:1px solid #ccc;' src='" . $theVar . "'></div></div><p style='font-size:.95em;'><a href='" . $postURL . "'>Latest post on Tumblr <i class='fa fa-tumblr-square'></i></a></p><p style='margin-bottom:0; font-size:.95em;'><a href='/dcaap'>DC Africana Archives Project at GW Libraries</a></p>";

$GLOBALS['dcaapItem'] = $dcaapItem;

/* End DCAAP Item. */

/* Creating blocks. */

 /**
 * Implements hook_block_info().
 */
function libsite_showcase_block_info() {
   $blocks = array();
   $blocks['library_hours_omeka_item'] = array(
     'info' => t("Latest Exhibit Item (Omeka)"),
     'region' => 'expanded_left',
     'visibility' => BLOCK_VISIBILITY_LISTED,
     'pages' => 'main',
     'weight' => 10,
   );
   $blocks['library_hours_dcaap_item'] = array(
     'info' => t("Latest DCAAP Item (Tumblr)"),
     'region' => 'expanded_right',
     'visibility' => BLOCK_VISIBILITY_LISTED,
     'pages' => 'main',
     'weight' => 10,
   );
   return $blocks;
 }

 /**
 * Implements hook_block_view().
 */

 function libsite_showcase_block_view($delta = '') {
   $block = array();

   switch ($delta) {
     case 'library_hours_omeka_item':
       $the_block = $GLOBALS['omekaItem'];
       $block = array(
         'subject' => t('Today in Gelman subject'),
         'title' => t('Latest Exhibit Item'),
         'content' => $the_block,
       );
       break;
      case 'library_hours_dcaap_item':
       $the_block = $GLOBALS['dcaapItem'];
       $block = array(
       'subject' => t('DCAAP'),
       'title' => t('Latest DCAAP Post'),
       'content' => $the_block,
       );
       break;  
     }
     return $block;
 }
