<?php

/* Get Latest Omeka Item */

$url = 'http://exhibits.library.gwu.edu/api/items';

$headerArray = get_headers($url, 1);
$howMany = ceil($headerArray['Omeka-Total-Results'] / 50);
$json_string = "http://exhibits.library.gwu.edu/api/items?page=" . $howMany;
$jsondata = file_get_contents($json_string);
$itemArray  = json_decode($jsondata, true); // decode JSON to associative array
$itemArrayDesc = array_reverse($itemArray);

//$omekaItem = "Test Text <a href='http://exhibits.library.gwu.edu/items/show/" . $itemArrayDesc['id']  . "'>" . $itemArrayDesc['element_texts'][0]['text'] . "</a>";

$i = 0;
foreach($itemArrayDesc as $info){
  $theVar = $info['files']['url'];
  $json_string2 = $theVar;
  $jsondata2 = file_get_contents($json_string2);
  $itemArray2  = json_decode($jsondata2, true);
    foreach($itemArray2 as $info2){
    }
  //echo "<li><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></li>";
  if (++$i == 7) break;
}

$omekaItem = "Test Text <a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a>";

$GLOBALS['omekaItem'] = $omekaItem;

/* Creating blocks. */

 /**
 * Implements hook_block_info().
 */
function libsite_showcase_block_info() {
   $blocks['library_hours_omeka_item'] = array(
     'info' => t("Latest Exhibit Item (Omeka)"),
     'region' => 'extended_left',
     'visibility' => BLOCK_VISIBILITY_LISTED,
     'pages' => 'main',
   );
 return $blocks;
 }

 /**
 * Implements hook_block_view().
 */

 function libsite_showcase_block_view($delta = '') {
   switch ($delta) {
     case 0:
       $the_block = $GLOBALS['omekaItem'];
       $block['subject'] = t('Today in Gelman subject');
       $block['title'] = t('Latest Exhibit Item');
       $block['content'] = $the_block;
       break;
     }
 return $block;
 }
