<?php

/* Get Latest Omeka Item. */

$url = 'http://exhibits.library.gwu.edu/api/items';

$headerArray = get_headers($url, 1);
$howMany = ceil($headerArray['Omeka-Total-Results'] / 50);
$json_string = "http://exhibits.library.gwu.edu/api/items?page=" . $howMany;
$jsondata = file_get_contents($json_string);
$itemArray  = json_decode($jsondata, true); // decode JSON to associative array
$itemArrayDesc = array_reverse($itemArray);

//$omekaItem = "Test Text <a href='http://exhibits.library.gwu.edu/items/show/" . $itemArrayDesc['id']  . "'>" . $itemArrayDesc['element_texts'][0]['text'] . "</a>";

$i = 0;
foreach($itemArrayDesc as $info){
  $theVar = $info['files']['url'];
  $json_string2 = $theVar;
  $jsondata2 = file_get_contents($json_string2);
  $itemArray2  = json_decode($jsondata2, true);
    foreach($itemArray2 as $info2){
    // gets file paths for images
    }
  // outputs things like echo "<li><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></li>";
  if (++$i == 7) break;
}

$omekaItem = "<div style='margin:.5em .1em .5em;'><img style='border:1px solid #ccc;' src='" . $info2['file_urls']['thumbnail'] . "'></div><p><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></p><p style='margin-bottom:0; font-size:.95em;'>See all our <a href='http://exhibits.library.gwu.edu/'>Online Exhibits <i style='font-size:.9em;' class='fa fa-external-link'></i></a></p>";

$GLOBALS['omekaItem'] = $omekaItem;

/* End Omeka Item. */

/* Get Latest DCAAP Tumblr Item. */

$dcaap_url = 'http://www.google.com/url?q=http%3A%2F%2Fapi.tumblr.com%2Fv2%2Fblog%2Fdcaap.tumblr.com%2Fposts&sa=D&sntz=1&usg=AFQjCNHtpPWVinpuBOd_jhrLT-Ib9QGyyw';

//$headerArray = get_headers($url, 1);
//$howMany = ceil($headerArray['Omeka-Total-Results'] / 50);
//$json_string = "http://exhibits.library.gwu.edu/api/items?page=" . $howMany;
$jsondata2 = file_get_contents($dcaap_url);
$itemArray2  = json_decode($jsondata2, true); // decode JSON to associative array
$itemArrayDesc2 = array_reverse($itemArray2);

$i = 0;
foreach($itemArrayDesc2 as $info){
  $theVar = $info['files']['url'];
  $json_string = $theVar;
  $jsondata = file_get_contents($json_string);
  $itemArray  = json_decode($jsondata, true);
    foreach($itemArray as $info2){
    // gets file paths for images
    }
  // outputs things like echo "<li><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></li>";
  if (++$i == 7) break;
}

$dcaapItem = "<div>" . $info['response']['posts']['slug'] . "</div>";

//$dcaapItem = "<div style='margin:.5em .1em .5em;'><img style='border:1px solid #ccc;' src='" . $info2['file_urls']['thumbnail'] . "'></div><p><a href='http://exhibits.library.gwu.edu/items/show/" . $info['id']  . "'>" . $info['element_texts'][0]['text'] . "</a></p><p style='margin-bottom:0; font-size:.95em;'>See all our <a href='http://exhibits.library.gwu.edu/'>Online Exhibits <i style='font-size:.9em;' class='fa fa-external-link'></i></a></p>";

$GLOBALS['dcaapItem'] = $dcaapItem;

/* End DCAAP Item. */

/* Creating blocks. */

 /**
 * Implements hook_block_info().
 */
function libsite_showcase_block_info() {
   $blocks = array();
   $blocks['library_hours_omeka_item'] = array(
     'info' => t("Latest Exhibit Item (Omeka)"),
     'region' => 'expanded_left',
     'visibility' => BLOCK_VISIBILITY_LISTED,
     'pages' => 'main',
   );
   $blocks['library_hours_dcaap_item'] = array(
     'info' => t("Latest DCAAP Item (Tumblr)"),
     'region' => 'expanded_right',
     'visibility' => BLOCK_VISIBILITY_LISTED,
     'pages' => 'main',
   );
   return $blocks;
 }

 /**
 * Implements hook_block_view().
 */

 function libsite_showcase_block_view($delta = '') {
   block = array();

   switch ($delta) {
     case 'library_hours_omeka_item':
       $the_block = $GLOBALS['omekaItem'];
       $block = array(
         'subject' => t('Today in Gelman subject');
         'title' => t('Latest Exhibit Item');
         'content' = $the_block;
       );
       break;
      case 'library_hours_dcaap_item':
       $the_block = $GLOBALS['dcaapItem'];
       $block = array(
       'subject' => t('DCAAP');
       'title' => t('Latest DCAAP Item');
       'content' => $the_block;
       );
       break;  
     }
     return $block;
 }
